# Generated by Django 5.0 on 2023-12-05 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_SERIES',
            fields=[
                ('A_Train_ID', models.CharField(default='A-001', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='INTER_TOWN',
            fields=[
                ('I_Route_ID', models.CharField(default='I-001', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LOCAL',
            fields=[
                ('L_Route_ID', models.CharField(default='L-001', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ROUTE',
            fields=[
                ('Route_ID', models.CharField(default='001', max_length=3, primary_key=True, serialize=False)),
                ('Train_Type', models.CharField(default='L', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='S_SERIES',
            fields=[
                ('S_Train_ID', models.CharField(default='S-001', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TRAIN_MODEL',
            fields=[
                ('Model', models.CharField(default='S-000', max_length=10, primary_key=True, serialize=False)),
                ('Max_Speed', models.CharField(default='000 kph', max_length=10)),
                ('No_of_Seats', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('No_of_Toilets', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('Reclining_Seats', models.BooleanField(default=False)),
                ('Folding_Tables', models.BooleanField(default=False)),
                ('Disability', models.BooleanField(default=False)),
                ('Luggage_Storage', models.BooleanField(default=False)),
                ('Vending_Machines', models.BooleanField(default=False)),
                ('Food_Service', models.BooleanField(default=False)),
                ('Train_Type', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='A_SERIES_ROUTING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Train_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.a_series')),
                ('L_Route_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.local')),
            ],
        ),
        migrations.CreateModel(
            name='S_SERIES_ROUTING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_Route_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.inter_town')),
                ('S_Train_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.s_series')),
            ],
        ),
        migrations.CreateModel(
            name='TRAIN',
            fields=[
                ('Train_ID', models.CharField(default='000001', max_length=6, primary_key=True, serialize=False)),
                ('Model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_operator.train_model')),
            ],
        ),
    ]
