# Generated by Django 5.0 on 2023-12-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_operator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_model',
            old_name='Disability',
            new_name='Disability_Access',
        ),
    ]
