# Generated by Django 4.1.6 on 2023-12-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_operator', '0002_rename_disability_train_model_disability_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='Train_Type',
            new_name='Route_Type',
        ),
    ]
