# Generated by Django 5.0 on 2023-12-05 09:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAINTENANCE',
            fields=[
                ('maintenance_num', models.CharField(default='0001', max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('Task_id', models.CharField(default='001', max_length=3, primary_key=True, serialize=False)),
                ('Task_name', models.CharField(default='Checking Train Brakes', max_length=25)),
                ('Date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('Crew_in_charge', models.CharField(default='J. Doe', max_length=25)),
                ('Condition', models.CharField(default='Good', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MAINTENANCE_LOGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_maintenance.maintenance')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.train')),
            ],
        ),
        migrations.CreateModel(
            name='MAINTENANCE_TASK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_maintenance.maintenance')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_maintenance.task')),
            ],
        ),
    ]
