# Generated by Django 5.0 on 2023-12-05 09:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('Customer_ID', models.CharField(default='0001', max_length=4, primary_key=True, serialize=False)),
                ('Last_Name', models.CharField(default='Doe', max_length=25)),
                ('Given_Name', models.CharField(default='John', max_length=25)),
                ('Middle_Initial', models.CharField(blank=True, default='A', max_length=2, null=True)),
                ('Birth_Date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Other', 'Other')], default='Male', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='STATION',
            fields=[
                ('Station_ID', models.CharField(default='AAA', max_length=25, primary_key=True, serialize=False)),
                ('Location', models.CharField(default=('BD', "Beaver's Dam"), max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('Ticket_number', models.CharField(default='0001', max_length=4, primary_key=True, serialize=False)),
                ('Date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('Customer_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_service.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TRIP',
            fields=[
                ('Trip_ID', models.CharField(default='00001', max_length=5, primary_key=True, serialize=False)),
                ('Origin', models.CharField(default='Allies’ Enclave', max_length=25)),
                ('Destination', models.CharField(default='Dancing Lawn', max_length=25)),
                ('Departure', models.TimeField(default=datetime.time(0, 0))),
                ('Arrival', models.TimeField(default=datetime.time(0, 0))),
                ('Cost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('Route_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.route')),
                ('Station_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.station')),
                ('Train_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_operator.train')),
            ],
        ),
        migrations.CreateModel(
            name='TRIP_LOGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.ticket')),
                ('Trip_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.trip')),
            ],
        ),
    ]
